create table if not exists tenants (
    id varchar(100) primary key,
    name varchar(255) not null,
    api_key_hash varchar(128) not null unique,
    plan_name varchar(100) not null,
    enabled boolean not null default true,
    created_at timestamp not null
);

create table if not exists gateway_routes (
    route_id varchar(100) primary key,
    path_pattern varchar(500) not null,
    target_url varchar(1000) not null,
    allowed_methods varchar(255) not null,
    enabled boolean not null default true,
    rate_limit_requests integer not null,
    rate_limit_window_seconds integer not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists request_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamp not null,
    tenant_id varchar(100),
    route_id varchar(100),
    method varchar(20) not null,
    path varchar(1000) not null,
    status_code integer not null,
    gateway_latency_ms double precision not null,
    backend_latency_ms double precision not null,
    rate_limit_decision varchar(50) not null,
    client_ip varchar(255),
    request_id varchar(100),
    gateway_instance_id varchar(255)
);

alter table request_logs add column if not exists gateway_instance_id varchar(255);

create index if not exists idx_request_logs_timestamp on request_logs (timestamp);
create index if not exists idx_request_logs_tenant_route on request_logs (tenant_id, route_id);
